name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via rsync SSH
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude='.git*' --exclude='_assets/' --exclude='_content/' --exclude='_preview/' --exclude='assets/_capturas/'
          path: ./
          remote_path: /home/u454444055/domains/palferia.me/public_html/
          remote_host: 147.93.93.199
          remote_port: 65002
          remote_user: u454444055
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
